const MAX_CHARACTERS_FIRST_NAME = 255;
const MAX_CHARACTERS_LAST_NAME = 255;
const MAX_CHARACTERS_USERNAME = 50;
const MIN_CHARACTERS_PASSWORD = 8;
const MAX_CHARACTERS_PASSWORD = 255;
const REGEX_EMAIL = /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/;
const MAX_CHARACTERS_RECORDING_NAME = 30;
const MAX_CHARACTERS_RECORDING_NOTES = 500;
const MAX_CHARACTERS_SUBJECT_NAMES = 255;

export default {
    MAX_CHARACTERS_FIRST_NAME: MAX_CHARACTERS_FIRST_NAME,
    MAX_CHARACTERS_LAST_NAME: MAX_CHARACTERS_LAST_NAME,
    MAX_CHARACTERS_USERNAME: MAX_CHARACTERS_USERNAME,
    MIN_CHARACTERS_PASSWORD: MIN_CHARACTERS_PASSWORD,
    MAX_CHARACTERS_PASSWORD: MAX_CHARACTERS_PASSWORD,
    REGEX_EMAIL: REGEX_EMAIL,
    MAX_CHARACTERS_RECORDING_NAME: MAX_CHARACTERS_RECORDING_NAME,
    MAX_CHARACTERS_RECORDING_NOTES: MAX_CHARACTERS_RECORDING_NOTES,
    MAX_CHARACTERS_SUBJECT_NAMES: MAX_CHARACTERS_SUBJECT_NAMES
};
